modules/c++/nitf/source/BufferedReader.cpp
modules/c++/nitf/source/BufferedWriter.cpp
modules/c++/nitf/source/Utils.cpp
modules/c++/nitf/tests/test_mt_record.cpp
modules/c/nitf/include/nitf/PluginIdentifier.h
modules/c/nitf/include/nitf/PluginRegistry.h
modules/c/nitf/include/nitf/TREDescription.h
modules/c/nitf/include/nitf/TREUtils.h
modules/c/nitf/shared/BANDSB.c
modules/c/nitf/shared/CSDIDA.c
modules/c/nitf/tests/test_geo_utils.c
modules/c/nrt/source/IOInterface.c

Added banners

---

modules/c++/nitf/include/import/nitf.hpp
modules/c++/nitf/include/nitf/IOStreamReader.hpp
modules/c++/nitf/source/IOStreamReader.cpp
modules/c++/nitf/wscript

Creates an nitf::IOInterface that can run from a CODA io::SeekableInputStream.

Added IO stream reader

---

modules/c/nitf/include/nitf/Field.h
modules/c/nitf/source/ImageIO.c

Timothy confirmed that he noticed the issue with a different program.

Remove bad byte swap and fix comment typos

---

modules/c++/nitf/include/nitf/Writer.hpp
modules/c++/nitf/source/Writer.cpp
modules/c++/nitf/tests/strip_invisible_segments.cpp
modules/c++/nitf/tests/test_writer_4.cpp
modules/c++/nitf/tests/test_writer_5.cpp

This is a program that Matt needs for Redwing.

Add program to strip out segments that aren't displayed

---

modules/c/nrt/include/nrt/DateTime.h
modules/c/nrt/source/DateTime.c
modules/c/nrt/unittests/test_nrt_datetime.c

This updates the time string parsing logic to infer the day of month and month when provided a year and day of year.  
FYI @clydestanfield

Infer day of month and month from day of year

---

modules/c/nrt/source/DateTime.c

place variable declarations at top of scope

---

modules/c++/nitf/tests/strip_invisible_segments.cpp
modules/c/nrt/unittests/test_nrt_datetime.c
modules/c/nrt/unittests/test_utils.c

See also issue #59 
and add a missing toString().

Correctly declare variables

---

modules/c++/nitf/include/nitf/ImageBlocker.hpp
modules/c++/nitf/include/nitf/ImageSubheader.hpp
modules/c++/nitf/include/nitf/NITFBufferList.hpp
modules/c++/nitf/source/ImageBlocker.cpp
modules/c++/nitf/source/ImageSubheader.cpp
modules/c++/nitf/source/NITFBufferList.cpp
modules/c++/nitf/unittests/test_nitf_buffer_list.cpp

Reviewed on SIX PR
FYI @JonathanMeans @christianwhite1193

Moving functionality from SIX into NITRO to support getting raw bytes

---

modules/c/j2k/source/OpenJPEGImpl.c
modules/c/nitf/include/nitf/ImageIO.h
modules/c/nitf/source/ImageIO.c

Ran into some issues while working. Unsure, but possibly related to https://github.com/mdaus/nitro/issues/11

Fix some memory errors that happen during cleanup

---

modules/c/nitf/source/Field.c

@asylvest
The control panel on the side isn't working right now... sorry.

Make message more useful for common error scenario

---

modules/c/nitf/source/DownSampler.c

This only compiles when I configure with --disable-python

Workaround for msvc bug

---

modules/c/j2k/shared/wscript
modules/c/nitf/include/nitf/Defines.h

Just hadn't ever updated this wscript like we did for the other TREs

Support static linking of J2K compressor/decompressor plugins

---

modules/c/nitf/source/DownSampler.c

Microsoft identified the source of the bug and provided a less-awful workaround.

Msvc better workaround

---

modules/c/nitf/shared/MSTGTA.c

Fix typo is MSTGTA.C

---

modules/c/nitf/unittests/test_image_io.c

Turns out C is super picky about what counts as a constant expression.

Remove warnings

---

modules/c++/nitf/include/nitf/BandInfo.hpp
modules/c++/nitf/source/BandInfo.cpp

Fixes https://github.com/mdaus/nitro/issues/158

Proper copy semantics for C++ BandInfo

---

modules/c/nitf/shared/RSMIDA.c

Fix field name for Illum Azimuth Angle in RSMIDA

---

modules/c/nitf/source/Reader.c

There's a formatting commit in here, so this is the "actual" diff: https://github.com/mdaus/nitro/commit/57da17d65db6a0f39ea3c723f318aade554ecf16
Somewhat high priority. I'd really like to get this into SIX master by 2 today.

Prevent fd leak

---

externals/coda-oss/.clang-format
externals/coda-oss/modules/c++/sys/include/sys/Err.h
externals/coda-oss/modules/drivers/numpy/wscript

Closes https://github.com/mdaus/nitro/issues/180

Sync externals

---

modules/c/nitf/source/TREUtils.c

Fixes https://github.com/mdaus/nitro/issues/182

Fix memory leak

---

modules/c++/nitf/include/nitf/TRE.hpp
modules/c++/nitf/source/TRE.cpp
modules/c++/nitf/unittests/test_tre_mods++.cpp

Fixes https://github.com/mdaus/nitro/issues/186

Handle too many decimals when setting float value for TRE field

---

modules/c/nitf/source/TREUtils.c

Closes https://github.com/mdaus/nitro/issues/189
See https://github.com/mdaus/nitro/commit/aead30a847c0956685b524b32c6522fdfee4a701 to ignore the formatting changes

Missing field error message

---

modules/c++/nitf/include/nitf/Object.hpp
modules/c++/nitf/source/DESegment.cpp
modules/c++/nitf/source/ImageWriter.cpp
modules/c++/nitf/unittests/test_image_writer.cpp
modules/c/nitf/source/ImageWriter.c

Fixes https://github.com/mdaus/nitro/issues/188

Don't ignore errors from failing ImageWriter construction

---

modules/wscript

Closes https://github.com/mdaus/nitro/issues/196

Escape backslashes in Windows path

---

modules/c++/nitf/include/nitf/DESubheader.hpp
modules/c++/nitf/include/nitf/Extensions.hpp
modules/c++/nitf/include/nitf/FileHeader.hpp
modules/c++/nitf/include/nitf/FileSecurity.hpp
modules/c++/nitf/include/nitf/GraphicSubheader.hpp
modules/c++/nitf/include/nitf/ImageSubheader.hpp
modules/c++/nitf/include/nitf/LabelSubheader.hpp
modules/c++/nitf/include/nitf/List.hpp
modules/c++/nitf/include/nitf/RESubheader.hpp
modules/c++/nitf/include/nitf/Record.hpp
modules/c++/nitf/include/nitf/TRE.hpp
modules/c++/nitf/include/nitf/TextSubheader.hpp
modules/c++/nitf/source/DESubheader.cpp
modules/c++/nitf/source/FileHeader.cpp
modules/c++/nitf/source/FileSecurity.cpp
modules/c++/nitf/source/GraphicSubheader.cpp
modules/c++/nitf/source/ImageSubheader.cpp
modules/c++/nitf/source/LabelSubheader.cpp
modules/c++/nitf/source/List.cpp
modules/c++/nitf/source/RESubheader.cpp
modules/c++/nitf/source/Record.cpp
modules/c++/nitf/source/TRE.cpp
modules/c++/nitf/source/TextSubheader.cpp

Make a bunch of "getters" `const`; it looks like somebody didn't know about `mutable`.

make a bunch of "getters" const

---

modules/c/nitf/shared/IMASDA.c
modules/c/nitf/shared/IMRFCA.c
modules/c/nitf/shared/MSDIRA.c
modules/c/nitf/shared/PRADAA.c
modules/c/nitf/shared/PTPRAA.c

This PR adds five TREs defined in [MIL-PRF-89034](https://earth-info.nga.mil/publications/specs/printed/89034/89034DPPDB.pdf):
- IMASDA
- IMRFCA
- MSDIRA
- PRADAA
- PTPRAA

Add five TREs defined in MIL-PRF-89034.

---

modules/c/nitf/CMakeLists.txt

build new TREs w/CMake

---

externals/coda-oss/modules/c++/except/include/except/Context.h
externals/coda-oss/modules/c++/except/include/except/Error.h
externals/coda-oss/modules/c++/except/include/except/Exception.h
externals/coda-oss/modules/c++/io/include/io/ByteStream.h
externals/coda-oss/modules/c++/io/include/io/FileInputStreamOS.h
externals/coda-oss/modules/c++/io/include/io/NullStreams.h
externals/coda-oss/modules/c++/io/include/io/OutputStream.h
externals/coda-oss/modules/c++/io/include/io/Seekable.h
externals/coda-oss/modules/c++/io/include/io/StringStream.h
externals/coda-oss/modules/c++/mt/include/mt/AbstractCPUAffinityInitializer.h
externals/coda-oss/modules/c++/mt/include/mt/BasicThreadPool.h
externals/coda-oss/modules/c++/mt/include/mt/GenerationThreadPool.h
externals/coda-oss/modules/c++/mt/include/mt/Singleton.h
externals/coda-oss/modules/c++/sys/include/sys/Conf.h
externals/coda-oss/modules/c++/sys/include/sys/DirectoryEntry.h
externals/coda-oss/modules/c++/sys/include/sys/Err.h
externals/coda-oss/modules/c++/sys/include/sys/Exec.h

latest from coda-oss to remove code-analysis warnings

latest from coda-oss to remove code-analysis warnings

---

Test/Test.vcxproj
modules/c++/nitro-c++.vcxproj
modules/c/nitf/ACCHZB.vcxproj
modules/c/nitf/ACCPOB.vcxproj
modules/c/nitf/ACFTA.vcxproj
modules/c/nitf/AIMIDB.vcxproj
modules/c/nitf/CSCRNA.vcxproj
modules/c/nitf/JITCID.vcxproj
modules/c/nitf/RPFHDR.vcxproj
modules/c/nitf/XML_DATA_CONTENT.vcxproj
modules/c/nitro-c.vcxproj
modules/c/nrt/include/nrt/Types.h
nitro.sln

need C-style enum with SWIG & build XML_DATA_CONTENT

---

modules/c++/nitf/include/nitf/ByteProvider.hpp
modules/c++/nitf/include/nitf/CompressedByteProvider.hpp
modules/c++/nitf/include/nitf/IOStreamWriter.hpp
modules/c++/nitf/include/nitf/ImageBlocker.hpp
modules/c++/nitf/include/nitf/ImageReader.hpp
modules/c++/nitf/include/nitf/NITFBufferList.hpp
modules/c++/nitf/include/nitf/System.hpp
modules/c++/nitf/include/nitf/Writer.hpp
modules/c++/nitf/include/nitf/cstddef.h
modules/c++/nitf/source/ByteProvider.cpp
modules/c++/nitf/source/CompressedByteProvider.cpp
modules/c++/nitf/source/IOStreamReader.cpp
modules/c++/nitf/source/IOStreamWriter.cpp
modules/c++/nitf/source/ImageBlocker.cpp
modules/c++/nitf/source/Writer.cpp
modules/c++/nitf/tests/test_buffered_read.cpp
modules/c++/nitf/tests/test_direct_block_round_trip.cpp
modules/c++/nitf/tests/test_round_trip.cpp
modules/c++/nitf/unittests/test_create_nitf++.cpp
modules/c++/nitf/unittests/test_image_segment_blank_nm_compression.cpp
modules/c++/nitf/unittests/test_nitf_buffer_list.cpp
modules/c++/nitf/unittests/test_writer_3++.cpp

Tweaks so that **six** (https://github.com/ngageoint/six-library) builds with **externals/nitro** updates.

tweaks so that six builds with nitro updates

---

modules/c++/nitf-c++.vcxproj
modules/c++/nitf-c++.vcxproj.filters
modules/c++/nitf/include/nitf/ByteProvider.hpp
modules/c++/nitf/include/nitf/CompressedByteProvider.hpp
modules/c++/nitf/include/nitf/ImageBlocker.hpp
modules/c++/nitf/include/nitf/ImageReader.hpp
modules/c++/nitf/include/nitf/NITFBufferList.hpp
modules/c++/nitf/include/nitf/System.hpp
modules/c++/nitf/include/nitf/coda-oss.hpp
modules/c++/nitf/source/ByteProvider.cpp
modules/c++/nitf/source/CompressedByteProvider.cpp
modules/c++/nitf/source/ImageBlocker.cpp
modules/c++/nitf/source/NITFBufferList.cpp
modules/c++/nitf/source/SegmentSource.cpp
modules/c++/nitf/tests/test_buffered_read.cpp
modules/c++/nitf/tests/test_round_trip.cpp
modules/c++/nitf/unittests/test_create_nitf++.cpp
modules/c++/nitf/unittests/test_image_loading++.cpp
modules/c++/nitf/unittests/test_image_segment_blank_nm_compression.cpp
modules/c++/nitf/unittests/test_nitf_buffer_list.cpp
modules/c++/nitf/unittests/test_writer_3++.cpp

Remove `nitf::byte`, replacing with `sys::byte` (or `uint8_t`) and an overload for `std::byte`.

remove nitf::byte

---

externals/coda-oss/modules/c++/gsl/include/gsl/gsl.h
externals/coda-oss/modules/c++/mt/include/mt/AbstractTiedThreadPool.h
externals/coda-oss/modules/c++/sys/include/sys/Conf.h
modules/c++/nitf/include/nitf/ByteProvider.hpp
modules/c++/nitf/source/ByteProvider.cpp
modules/c++/nitf/source/SegmentSource.cpp

Latest from https://github.com/mdaus/coda-oss

latest from coda-oss

---

CMakeLists.txt
modules/c/nitf/source/ImageSubheader.c
modules/c/nrt/source/HashTable.c

Revert c99 changes ... back to compiling with C90, a 31-year-old standard! 😱

revert c99 changes

---

.gitignore
modules/c++/nitf/CMakeLists.txt
modules/c++/nitf/unittests/test_tre_create++.cpp

Add unittest for https://github.com/mdaus/nitro/issues/329

unittests for issue #329

---

ReleaseNotes.md
externals/coda-oss/ReleaseNotes.md
externals/coda-oss/modules/c++/config/include/config/Version.h
externals/coda-oss/modules/c++/except/include/except/Context.h
externals/coda-oss/modules/c++/include/TestCase.h
externals/coda-oss/modules/c++/logging/unittests/test_exception_logger.cpp
externals/coda-oss/modules/c++/math.poly/tests/test_OneD_templates.cpp
externals/coda-oss/modules/c++/mt/include/mt/WorkSharingBalancedRunnable1D.h
externals/coda-oss/modules/c++/numpyutils/unittests/test_num_elements.cpp
externals/coda-oss/modules/c++/re/unittests/test_regex.cpp
externals/coda-oss/modules/c++/sio.lite/include/sio/lite/FileWriter.h
externals/coda-oss/modules/c++/str/include/str/EncodedString.h
externals/coda-oss/modules/c++/str/include/str/Manip.h
externals/coda-oss/modules/c++/str/source/EncodedString.cpp
externals/coda-oss/modules/c++/str/source/Encoding.cpp
externals/coda-oss/modules/c++/str/unittests/test_base_convert.cpp
externals/coda-oss/modules/c++/sys/include/sys/filesystem.h
externals/coda-oss/modules/c++/sys/include/sys/sys_filesystem.h
externals/coda-oss/modules/c++/sys/source/DateTime.cpp
externals/coda-oss/modules/c++/sys/source/sys_filesystem.cpp
externals/coda-oss/modules/c++/sys/unittests/test_os.cpp
externals/coda-oss/modules/c++/sys/unittests/test_path.cpp
externals/coda-oss/modules/c++/xml.lite/unittests/test_xmlattribute.cpp
externals/coda-oss/modules/c++/xml.lite/unittests/test_xmlelement.cpp
modules/c++/nitf/include/nitf/exports.hpp
modules/c++/nitf/unittests/test_tre_mods++.cpp

[coda-oss release 2022-05-03](https://github.com/mdaus/coda-oss/tree/release/2022-05-03)

coda-oss release 2022-05-03

---

modules/c++/nitf/source/DecompressionInterface.cpp

Function was never fully implemented

Fill out adapter free block which is used for nitf decompression

---

.gitattributes
externals/coda-oss/.gitattributes
externals/coda-oss/ReleaseNotes.md
externals/coda-oss/modules/c++/config/include/config/Version.h

[coda-oss 2023-10-23](https://github.com/mdaus/coda-oss/releases/tag/2023-10-23).

CODA-OSS 2023-10-23
