mdaus/nitro

- modules/c/j2k/wscript
This meant it just straight up tried to copy itself to the installation directory, even during the build step.  Identified in SIX: https://github.com/ngageoint/six-library/issues/37.
@chvink @kjurka
> j2k_config.h was getting installed via copyfile rather than the normal clean way

- modules/c/nitf/source/BandSource.c
MSVC 11.0 still requires the variables to be the first thing in C functions.
> Moved the variable declarations to the top of functions

- modules/c++/nitf/include/nitf/BandSource.hpp
- modules/c++/nitf/include/nitf/PluginRegistry.hpp
- modules/c++/nitf/source/PluginRegistry.cpp
- modules/c++/nitf/tests/test_static_plugin.cpp
- modules/c++/nitf/wscript
- modules/c/j2k/shared/wscript
- modules/c/jpeg/wscript
- modules/c/nitf/include/nitf/Defines.h
- modules/c/nitf/include/nitf/PluginRegistry.h
- modules/c/nitf/shared/wscript
- modules/c/nitf/source/PluginRegistry.c
- modules/c/nitf/wscript
Adding back in the ability to link TREs in statically rather than requiring them to be built as plugins.  Support very similar to this was in NITRO previously but was removed when we updated to waf 1.7 a few years ago.  Two changes with this support:
1. TREs are still built only as plugins by default.  You need to use the new configure option `--enable-static-tres` to get this support.
2. Rather than a single static library that contains all the TREs, each TRE is built individually.  This lets you potentially target and link in only the TRE(s) you care about.
Resurrected `test_static_plugin.cpp` and got it linking with the TRE it uses properly.  Use that as an example of both how to use this support in the code as well as how to link properly.
> Add in support for static TREs

- modules/c/nitf/shared/wscript
Otherwise waf msvs gets confused (the directories that build.py automatically adds on don't exist)
> Need to remove adding include directory to TRE targets

- modules/c++/nitf/include/nitf/Writer.hpp
- modules/c++/nitf/source/Writer.cpp
- modules/c/nitf/include/nitf/Writer.h
- modules/c/nitf/source/Writer.c
Making some functions in `Writer` public so that you can write out only pieces of a NITF directly yourself rather than going through the normal `Writer` interface that takes care of this for you.  Only use this if you know what you're doing.
Full disclosure: this has only been tested in writing SICD NITFs.
@JonathanMeans 
@chvink
> Support writing pieces of a NITF

- modules/c/nitf/source/ImageIO.c
- modules/c/nitf/source/Writer.c
Though the underlying structures all kept 64-bit offsets, there was a spot in our calculations where we used a 32-bit value to calculate the offset into an image segment, so if the caller requested a start row that ended up being > 4 GB into the image segment, the correct file offset was not used in the eventual read.
Fixed a few compiler warnings while I was in the code too.
FYI @JonathanMeans
> Fixed a bug when the offset into an image segment was > 4 GB

- modules/c++/nitf/source/IOHandle.cpp
- modules/c++/nitf/source/MemoryIO.cpp
- modules/c/nitf/source/BandSource.c
- modules/c/nitf/source/ImageIO.c
- modules/c/nrt/include/nrt/Types.h
* There is a `#define` we need to look for if we have gnu or not
* The `interface` keyword is reserved on Windows... not sure why VS doesn't care but gcc does
FYI @JonathanMeans
> Updates to support gcc on Windows

- modules/c++/nitf/include/nitf/Field.hpp
- modules/c++/nitf/unittests/test_field++.cpp
- modules/c/nitf/source/Field.c
This gets rid of some duplicate code at the cost of some template metaprogramming complication.  The main motivation is to address cases like described in https://github.com/ngageoint/six-library/pull/191 where the compiler (OS X in this case) doesn't figure out to use the `nitf::Uint64` cast operator for `size_t`.  Now it's just templated so it should auto-magically find it.
Also added conversions in the base C layer for 1 byte signed/unsigned ints... apparently this never worked in the past.
Added a unittest to make sure all conversions still work.
> Template nitf::Field cast operator

- modules/c/nitf/shared/CCINFA.c
This adds the CCINFA TRE (RFC NTB-084, STDI-0002 Vol 1, adds appendix AG).
Sample data is available at http://labs1.sigmabravo.com/girder#collection/59830930e98bf705230f3b4d/folder/598309d6e98bf705230f3b59
> Initial commit for CCINFA TRE.

- modules/c/nrt/include/nrt/Utils.h
- modules/c/nrt/source/Utils.c
- modules/c/nrt/unittests/test_utils.c
The two altered functions are only used together in actual code. The tests where they're used alone still pass.
I found a couple other problems while I was digging. Wanted to get this part of the fix up quickly so Dennis can get past what he's working on.
@dfeng1
> Simply handling W/S DMS; fix bug with 0 degrees

- modules/c++/nitf/include/nitf/BufferedReader.hpp
- modules/c++/nitf/source/BufferedReader.cpp
Previously `BufferedReader` only kept a single constant `mBufferSize` value which was the allocated size of the buffer.  When the file position was updated to be near enough the end of the file that `readNextBuffer()` couldn't read in `mBufferSize` bytes, that method correctly read in fewer bytes, but subsequent spots like `readImpl()` and `tellImpl()` treated it as if it had been a full `mBufferSize` bytes that were read in.  We need to use two variables to keep track of this.
Also improved `seekImpl()` - if you are seeking to a spot you already read in, there's no reason to trigger a read yet.
FYI to @msciaramitaro and @clydestanfield... I guess we didn't have code using `BufferedReader` or else we would have hit this a long time ago.
@JonathanMeans double-check my pointer arithmetic …
> BufferedReader did not handle seeking to end of file properly

- modules/c++/nitf/include/nitf/BufferedReader.hpp
- modules/c++/nitf/source/BufferedReader.cpp
Ugh - in trying to make the ternary operator line that assigns `bufferSize` more legible in `readNextBuffer()` by adding some `()`s, I put the opening one in the wrong spot which broke the calculation.
Breaking this out into multiple lines now to make it more clear, and having one less call to `getCurrentOffset()` as I'm not sure if that's expensive or not.  Similarly, saving off the file length as this'll never change and we check it every time we call `readImpl()`.
> Fixed bug in bufferSize calculation due to misplacing a parenthesis

- modules/c++/nitf/include/nitf/ImageSegmentComputer.h
- modules/c++/nitf/source/ImageSegmentComputer.cpp
This generalizes the logic in SIX which deals with breaking large images into multiple image segments per the NITF spec requirements.
FYI @JonathanMeans
> Moving image segment logic from SIX into NITRO

- modules/c/nrt/source/Utils.c
- modules/c/nrt/unittests/test_utils.c
This fixes two bugs:
1. `nrt_Utils_decimalToGeographic()` was converting everything with 0 degrees to be negative
2. `nrt_Utils_geographicLat/LonToCharArray()` did not handle 0 degrees properly
> Fix bugs in utilities for manipulating coordinates

- modules/c/jpeg/source/LibjpegDecompress.c
Valgrind was complaining on line 1480 because markerList was never initialized to anything. This should fix https://github.com/mdaus/nitro/issues/11
This field actually gets constructor in implStart. So I think this problem would only happen if you create a reader, then get rid of it before you do anything with it.
> Properly initialize JPEG decompression control

- modules/c++/nitf/include/nitf/ImageBlocker.hpp
- modules/c++/nitf/source/ImageBlocker.cpp
- modules/c++/nitf/unittests/test_image_blocker.cpp
This logic is buried in the C layer inside the image writer somewhere in terms of the blocking itself.  This exposes the blocking functionality in a modular way and allows you to provide an arbitrary portion of the image (as a multiple of blocks) which we'll eventually use in a SIDDByteProvider.
> Adding ImageBlocker

- modules/c++/nitf/include/nitf/ByteProvider.hpp
- modules/c++/nitf/source/ByteProvider.cpp
Generalized the SIX ByteProvider - this makes it easy to ask NITRO for a portion of the NITF in terms of raw bytes so you can write it yourself.
See https://github.com/ngageoint/six-library/pull/220/ for more details.
FYI @JonathanMeans @christianwhite1193
> Adding generalized ByteProvider

- modules/c++/nitf/source/ImageBlocker.cpp
Need one more spot to check for this... otherwise `findSegmentRange()` sets all its output values to the numeric max value but we still incorrectly end up in the following `for` loop
> Add check for no rows

- modules/c++/nitf/source/ImageSegmentComputer.cpp
- modules/c++/nitf/unittests/test_image_segment_computer.cpp
The update itself was trivial. I think I have enough tests in there to verify everything. The testKnownCase is Joe's case. I verified that has been fixed. As part of that test I also verified that going through a ImageBlocker would not throw an exception. This should cover the issue I was seeing.
@JonathanMeans
> Force Image Segments to be Multiple of Block Size

- modules/c++/nitf/include/nitf/ImageBlocker.hpp
It's useful to get the number of cols / block `ImageBlocker` is using
FYI @JonathanMeans
> Adding convenience method

- modules/python/nitf/samples/strip_invisible_segments.py
- modules/python/nitf/source/generated/nitropy_wrap.cxx
- modules/python/nitf/source/nitro.i
Someone wants to use Python to read in a NITF image of size > 2^32 - 1 bytes. A size_t should be able to handle it on a 64-bit system.
> Python should be able to read NITF with size_t bytes

- modules/c++/nitf/source/ByteProvider.cpp
ByteProvider interface already supports writing multiple DES buffers. Unfortunately, the subheader length is not correct because the ByteStream it uses to tally buffer size continues to increment.
> Fixing NITF subheader length for multiple DES writes

- modules/c/j2k/source/OpenJPEGImpl.c
We were subtracting off an offset that we shouldn't have been, resulting in OpenJPEG erroring out reading the last tile thinking it didn't have enough bytes (unless the NITF happened to contain other content after the last image segment).
> Fixed bug in J2K reader that was causing errors reading last tile

- modules/c++/nitf/include/nitf/ImageBlocker.hpp
- modules/c++/nitf/source/ImageBlocker.cpp
This makes it easier to perform blocking on the fly as part of another (likely threaded) operation
> Adding static block() method that performs a single block operation

- modules/c++/nitf/source/ByteProvider.cpp
- modules/c++/nitf/source/CompressedByteProvider.cpp
The memory's all contiguous so can return this as a single buffer
Removing unused standalone function in unnamed namespace (it had gotten moved to a member function)
> CompressedByteProvider can return a single image buffer

- modules/c++/nitf/include/nitf/CompressedByteProvider.hpp
- modules/c++/nitf/source/CompressedByteProvider.cpp
This fixes a bug that occurred when writing NITFs > 10 GB that were splitting into multiple image segments but this maxNumRowsPerSegment was just defaulting to 0 which was causing incorrect rows to be computed.  This always has to be in sync with the Record, so we can just infer this.
> Setting maxRowsPerSegment is problematic - should be inferring it

- modules/c++/nitf/unittests/test_image_segment_blank_nm_compression.cpp
- modules/c/nitf/source/ImageIO.c
When we updated the inside location with the latest code it introduced a number of new errors.  After tracing the code I noticed that the totalBlocksWritten was in the block IO object and this is not unique.  We had to move this variable to the nitf block for that is unique for the segment. I also had to update the test so it would fail properly for these conditions.   I made it have more than just one row of Blocks per segment and instead of filling all white and then the blank with black I filled everything black and then any segment that is not suppose to be blank I wrote a single white value in the center of the segment.  This produced the proper error I was looking for and now this should handle the worst possible case. and fix the problem
> Bug fix for the totalBlocksWritten

- modules/c/nrt/source/IOInterface.c
- modules/c/nrt/unittests/test_buffer_adapter.c
Both `lseek` and `SetFilePointer` treat seeking past EOF as valid, and any reads that occur after EOF just return 0 bytes. This should fix that EOF error message.
BufferAdapter will still error on writing past EOF rather than trying to emulate what Unix or Windows system calls will do, since this works with a fixed buffer, and if that's what you're trying to do, you're probably using the wrong thing entirely.
> Update BufferAdapter to seek past EOF like Unix and Windows interface

- modules/c/nrt/source/IOInterface.c
I agree that this is the right thing to do. Otherwise the size will always report as 0 when you just want to read. 
This does make things slightly more clunky if you want to use it for writing, but this is already not very good for writing. If someone wants to know how many bytes have been written, they should probably be using `BufferAdapter_tell()` anyway.
> Fix BufferAdapter_getSize

- modules/c++/nitf/include/nitf/BandInfo.hpp
- modules/c++/nitf/source/BandInfo.cpp
This reverts commit f2ee1678c2c73f66655f1dd87fecfad1959aeeae, reversing
changes made to 3f51d12e51b5a1b6c3d724214c8c0647ae8692ed.
Copy constructor leads to segfaults.
> Revert "Merge pull request #159 from mdaus/band_info_copy"

- modules/c/nitf/source/PluginRegistry.c
- modules/wscript
One commit is just running a formatter on PluginRegistry.c. See [this commit](https://github.com/mdaus/nitro/commit/e8ffab7747c190e4fb4e65811a7f49c6b82aeca6) for the meaningful changes.
> Use compiled-in NITF_PLUGIN_PATH if environment variable not set

- modules/c++/nitf/include/nitf/TRE.hpp
- modules/c++/nitf/source/TRE.cpp
- modules/c++/nitf/unittests/test_tre_mods++.cpp
Fixes https://github.com/mdaus/nitro/issues/184
I forgot to run the formatter separately for TRE.cpp. The only "real" change in that file is the implementation of `updateData`
> Allow setField to work with binary TRE fields

- modules/c/nitf/source/ImageIO.c
The bug is in lines 4960-4965 of modules/c/nitf/source/ImageIO.c. myResidual is an unsigned integer, so it cannot be negative. The "if (myResidual < 0)" case can never happen. Instead of myResidual being set to 0 in such a case, it is a very large positive number, which can result it a seg fault.
> Bug in ImageIO myResidual calculation can cause seg fault 

- modules/java/CMakeLists.txt
- modules/java/nitf.imageio/src/java/nitf/imageio/ImageIOUtils.java
- modules/java/nitf.imageio/src/java/nitf/imageio/NITFReader.java
- modules/java/nitf/src/java/nitf/BandSource.java
- modules/java/nitf/src/java/nitf/DownSampler.java
- modules/java/nitf/src/java/nitf/NITFObject.java
While trying to build on a new Ubuntu box with openjdk 11 (`javac 11.0.8`), I hit a problem:
```
[ 99%] Building Java objects for nitf-java.jar
warning: [options] bootstrap class path not set in conjunction with -source 5
error: Source option 5 is no longer supported. Use 6 or later.
error: Target option 1.5 is no longer supported. Use 1.6 or later.
make[2]: *** [modules/java/nitf/CMakeFiles/nitf-java.dir/build.make:133: modules/java/nitf/CMakeFiles/nitf-java.dir/java_compiled_nitf-java] Error 2
make[1]: *** [CMakeFiles/Makefile2:12293: modules/java/nitf/CMakeFiles/nitf-java.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
This PR updates to 1.8, and fixes some warnings associated with that. There is more that could be done, but this gets it going again.
> java: update to supported version

- modules/c/nitf/CMakeLists.txt
- modules/c/nitf/shared/MATESA.c
This TRE is defined in STDI-0002-1 Appendix AK: "MATESA 1.0" and is used in the SNIP Reference Implementation Products (RIPs). 
Here is a sample of the output:
```
--------------- MATESA TRE (897) - (MATESA) ---------------
CUR_SOURCE (Current File/Segment Source) = [EO-1_HYPERION                             ]
CUR_MATE_TYPE (Current File/Segment Mate Type) = [FTITLE          ]
CUR_FILE_ID_LEN (Length of the CUR_FILE_ID field) = [0063]
CUR_FILE_ID (ID of the Current File/Segment) = [07APR2005_Hyperion_331406N0442000E_SWIR172_001_L1R-01B-BIP-GLAS]
NUM_GROUPS (Number of Mate Relationship Groups) = [0005]
RELATIONSHIP[0] (Mate Relationship) = [RADIOMTRC_CALIB         ]
NUM_MATES[0] (Number of Mates in the Group) = [0001]
SOURCE[0][0] (Mate Source) = [EO-1_HYPERION …
```
> tre: add MATESA support

- externals/coda-oss/modules/c++/sys/include/sys/Filesystem.h
- externals/coda-oss/modules/c++/sys/source/Filesystem.cpp
- modules/c++/nitf/include/nitf/BufferedReader.hpp
- modules/c++/nitf/include/nitf/BufferedWriter.hpp
- modules/c++/nitf/tests/strip_invisible_segments.cpp
- modules/c++/nitf/tests/test_direct_block_round_trip.cpp
- modules/c++/nitf/tests/test_handles.cpp
- modules/c++/nitf/tests/test_image_loading++.cpp
- modules/c++/nitf/tests/test_round_trip.cpp
- modules/c++/nitf/tests/test_tre_create.cpp
- modules/c++/nitf/tests/test_writer_4.cpp
- modules/c++/nitf/tests/test_writer_5.cpp
- modules/c++/nitf/unittests/test_image_writer.cpp
use `std::shared_ptr` and filesystem instead of `mem::` and `sys::` routines
> use std::shared_ptr and filesystem instead of mem:: and sys:: routines

- modules/c++/nitf/include/nitf/ByteProvider.hpp
- modules/c++/nitf/include/nitf/CompressedByteProvider.hpp
- modules/c++/nitf/include/nitf/ImageBlocker.hpp
- modules/c++/nitf/include/nitf/ImageReader.hpp
- modules/c++/nitf/include/nitf/NITFBufferList.hpp
- modules/c++/nitf/include/nitf/System.hpp
- modules/c++/nitf/include/nitf/cstddef.h
- modules/c++/nitf/source/ByteProvider.cpp
- modules/c++/nitf/source/CompressedByteProvider.cpp
- modules/c++/nitf/source/IOStreamReader.cpp
- modules/c++/nitf/source/IOStreamWriter.cpp
- modules/c++/nitf/source/ImageBlocker.cpp
- modules/c++/nitf/tests/test_buffered_read.cpp
- modules/c++/nitf/tests/test_round_trip.cpp
- modules/c++/nitf/unittests/test_create_nitf++.cpp
- modules/c++/nitf/unittests/test_image_segment_blank_nm_compression.cpp
- modules/c++/nitf/unittests/test_nitf_buffer_list.cpp
`std::byte` -> `nitf::byte` until we can use C++17 everywhere.
> std::byte -> nitf::byte until we can use C++17 everywhere

- modules/c++/nitf/include/nitf/System.hpp
get **coda-oss** `#include`s via **coda-oss.hpp** to augment `std`.
> get coda-oss #includes via coda-oss.hpp to augment "std"

- modules/c/CMakeLists.txt
- modules/c/cgm/CMakeLists.txt
- modules/c/j2k/CMakeLists.txt
- modules/c/jpeg/CMakeLists.txt
- modules/c/nitf/CMakeLists.txt
- modules/c/nrt/CMakeLists.txt
The CMake build does not support building shared libraries correctly on windows for `nrt-c`, `nitf-c`, `cgm-c` .
This PR adds an option `-DBUILD_SHARED=ON` to tell CMake to build modules that support it as shared libraries.
NOTE: The existing `BUILD_SHARED_LIBS` is not used because not all libraries support or have correct dllexport statements for windows.  These are mostly the c++ projects.
Additionally the `j2k-c` library and tests are not built if `-DENABLE_J2K=OFF` is passed.
> CMake: Build c libraries, in Windows, as DLLs

- modules/c/nitf/source/NitfWriter.c
If the test https://github.com/mdaus/nitro/blob/e77ddad8f4e93c69cb3de1154396d9237a014ae7/modules/c/nitf/source/NitfWriter.c#L865 fails and returns, the array `writer->imageWriters` can not be left in a non-determinate state.
NOTE:   I also question this test because MIL-STD2500C defines the image length as the **compressed** image size if the image is compressed, This allows actual images to exceed 9,999,999,998 bytes .
> Null init imager writers before loop with error

- modules/c/nitf/CMakeLists.txt
- modules/c/nitf/source/Record.c
- modules/c/nitf/unittests/test_moveTREs.c
- Add TRE header size to TRE size calulation in `move TREs`
- Change macro UNMERGE_SEGMENT to C function
- Support unmerge if a TRE_OVERFLOW already exists in Header
1. Open NITF with TRE_OVERFLOW
2. Add New TRE to header (without merging TRE_OVERFLOW)
- Unit Test for both cases
> Fix length calculation for moveTRE and unmergeTREs

- modules/c++/nitf/include/nitf/ImageSubheader.hpp
Looks like this line is causing a compile error for me.
`getCornersAsLatLons_` modifies corners so I don't think the const here is correct?
> Fix invalid const cast error

- modules/c++/nitf/CMakeLists.txt
When NITRO switched from waf to CMake, the `show_nitf++` app was not included as a CMake build target. The source file still exists, so this is a minimal change to add the `show_nitf++` executable build target.
See #438.
> Re-add show_nitf++ app

- modules/c/jpeg/CMakeLists.txt
Decompression handlers are looked up in the plugin registry, so
we need to build as a plugin for this to be found.
Tested reading a "M3" compressed NITF from the AFRL Greene 07
dataset.  Closes #481.
> Build jpeg decompression as a plugin.

- conanfile.py
This fixes an issue for Conan builds where the `ENABLE_J2K` CMake option was not propagated from coda-oss.
The branch name was also removed from the conan package version string. Branch names with slashes are incompatible with Conan package versioning, and there can be more than one branch at the same commit resulting in separate builds needed for each branch name.
> Fix conan build issues

- modules/c++/nitf/apps/show_nitf++.cpp
TREs in the file header extended header aren't displayed. The previous code dumped the user defined header twice - looks like cut-n-paste of line 366.
> apps: fix display of TREs from file extended header section

- ReleaseNotes.md
- modules/c++/nitf/include/nitf/Version.hpp
- modules/c/nrt/include/nrt/Version.h
* [coda-oss](https://github.com/mdaus/coda-oss) release [2022-03-10](https://github.com/mdaus/coda-oss/releases/tag/2023-03-10)
* Sanitize tar-file extraction; conan tweaks.
* Final 🤞🏻 C++11 release; future releases will be C++14 from [main](https://github.com/mdaus/nitro/tree/main).
> NITRO 2.10.13

- modules/c++/nitf/include/nitf/Object.hpp
- modules/c++/nitf/source/FileHeader.cpp
- modules/c++/nitf/source/TRE.cpp
- modules/c++/nitf/tests/test_create++.cpp
- modules/c++/nitf/tests/test_extract.cpp
- modules/c++/nitf/tests/test_fhdr_clone++.cpp
- modules/c++/nitf/tests/test_functional.cpp
- modules/c++/nitf/tests/test_j2k_nitf_read_region.cpp
- modules/c++/nitf/tests/test_read_acftb.cpp
- modules/c++/nitf/unittests/test_j2k_loading++.cpp
Change using the `FmtX()` macro to calling the `str::Format()` method.
> FmtX() -> str::Format()

- .github/workflows/codeql.yml
- .github/workflows/frequent_check.yml
- .github/workflows/main.yml
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12
> update various actions to latest versions

- externals/coda-oss/modules/c++/include/TestCase.h
- externals/coda-oss/modules/c++/sys/source/OSWin32.cpp
> Coda oss 20240920
